name: PR Check

on:
  pull_request:
    branches: [dev]
    types: [closed]

jobs:
  check:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Hello World
        run: echo "Hello World"